<?php

namespace AppBundle\Repository;

/**
 * produitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function findParDate($dateajout)
    {
        
        $query = $this->getEntityManager()->createQuery(
            'SELECT p
            FROM AppBundle:Produit p
            WHERE p.dateajout = :dateajout
            ORDER BY p.dateajout ASC'
        )->setParameter('dateajout', $dateajout);
        
        $produits = $query->getResult();
        return $produits;

    }

    public function findParDate2($date)
    {

        $query = $this->createQueryBuilder('p')
            ->where('p.dateajout = :date')
            ->setParameter('date', $date)
            ->orderBy('p.dateajout', 'ASC')
            ->getQuery();

        $produits = $query->getResult();
        return $produits;

    }

}
