<?php

namespace AppBundle\Repository;

/**
 * ProduitFamilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitFamilleRepository extends \Doctrine\ORM\EntityRepository
{
}
